### PR TITLE
[#180] remove IOException from FileUtils signature

### LINKED ISSUE #180: FileUtils can never throw an IOException
Hi,

I did a quick check of `FileUtils::getFileAndDirectoryNames`

Signature:
```
public static List<String> getFileAndDirectoryNames( File directory, String includes, String excludes,
                                                         boolean includeBasedir, boolean isCaseSensitive,
                                                         boolean getFiles, boolean getDirectories )
        throws IOException;
```

Source:
https://github.com/codehaus-plexus/plexus-utils/blob/1f93cc8583f872b7bc01bef1dc32979f0a2335bb/src/main/java/org/codehaus/plexus/util/FileUtils.java#L1833-L1906

It seems it can never throw an IOException.
If we removed it, a lot of Maven Mojos could be made MUCH simpler.

One of the reasons is that `canGenerateReport` is called both in `execute` and `executeReport`. One throws a  `MojoExecutionException`, the other one a `MavenReportException`, but `canGenerateReport` can throw neither. This means, that it is impossible to deal with IOExceptions in Maven Reports anyway.

### PR DESCRIPTION
**Pull request by bmarwell**
fixes #180 

Sadly, this is a breaking change – make it a new major version (and add other similar changes, too!).

### CODE REVIEW

**Comment by olamy** [comment]
ditto that will break a lot of stuff

**Comment by bmarwell** [comment]
Still think it's worth it. I adds so much noise to Mojos (especially reports) that this is a great fix.

**Comment by michael-o** [comment]
Who is actually using PU outside of Codehaus or Maven space?

**Comment by gnodet** [comment]
> Who is actually using PU outside of Codehaus or Maven space?

I don't really think it matters.  If it goes inside a major release, users will have to adjust, but the change makes sense to me.

**Review by gnodet — APPROVED** [review]

**Comment by bmarwell** [comment]
FWIW, those have to be reflected in maven-utils as well.

> > Who is actually using PU outside of Codehaus or Maven space?
> 
> I don't really think it matters. If it goes inside a major release, users will have to adjust, but the change makes sense to me.

in this case, I was using it for the [taglist-maven-plugin](https://github.com/mojohaus/taglist-maven-plugin). Someone was using it in `canGenerateReport()`. This method can neither throw a `MojoExecutionException` nor a `MavenReportException`, which is problematic:

https://github.com/mojohaus/taglist-maven-plugin/pull/56/commits/dac102d3aa6af3357aded46a04cecfb6f8a10d80#diff-d78dd9fa5c0bfb4f18b93522e585ad3e35dc9eb0315763dd26e7ea7465d04764R466-R473

For this reason, I created yet another issue: https://issues.apache.org/jira/browse/MNG-7393

I do not think throwing a `RuntimeException` is particularly helpful here, though.

**Review by slachiewicz — APPROVED** [review]

**Comment by michael-o** [comment]
Question: When the code will move to NIO 2, will `IOExceptions` come back?

**Comment by bmarwell** [comment]
> Question: When the code will move to NIO 2, will `IOExceptions` come back?

Good point. Not at PC today, but from memory: yes, probably.

**Comment by michael-o** [comment]
> > Question: When the code will move to NIO 2, will `IOExceptions` come back?
> 
> Good point. Not at PC today, but from memory: yes, probably.

If this evaluates to true, then this PR should be dropped.

**Comment by michael-o** [comment]
@bmarwell Do you still want to hold onto this PR although I have a provided a reason not to?

**Comment by bmarwell** [comment]
@michael-o Good question. I initially opened this issue because of how the maven report works. But we can deal with it later as well.

**Pull request closed without merging**
