### PR TITLE
NIO 8

### PR DESCRIPTION
**Pull request by mkarg**
Work in progress: Using NIO 8 to allow better offloading / performance. PR stays in draft state until Plexus Utils is allowed to use Java 8 APIs.

### CODE REVIEW

**Comment by mkarg** [comment]
@michael-o Certainly this PR fails CI now, as the parent is not published anywhere. Is there some nightly build we can refer to by this branch?

**Comment by michael-o** [comment]
I will try to push master tomorrow or tonight.

**Comment by olamy** [comment]
plexus pom 7 release done. should be in central in few hours.
have fun :)

**Comment by olamy** [comment]
please do not forget to add label to your pr so we have a nice generated release note

**Review by michael-o — APPROVED** [review]

**Pull request merged**
