### PR TITLE
Always preserve dominant node value (even if empty)

### LINKED ISSUE #216: Xpp3DomUtils#mergeIntoXpp3Dom() must not override the dominant value in case it is empty
Although that behaviour is also stated in its [javadoc](https://github.com/codehaus-plexus/plexus-utils/blob/8a9147a07332b9ef554c9aa695aa4105532167e2/src/main/java/org/codehaus/plexus/util/xml/Xpp3DomUtils.java#L98) it is highly unexpected.  Rather a dominant empty value element should take precedence over the same named recessive element value. This would be necessary for https://issues.apache.org/jira/browse/MNG-6434 to work as expected.

### PR DESCRIPTION
**Pull request by kwin**
This closes #216

### CODE REVIEW

**Comment by kwin** [comment]
I tested this against the Maven Integration Tests and there were no failures.

**Comment by michael-o** [comment]
Can you run this change against all Maven Plugin Tools ITs?

**Review by michael-o — APPROVED** [review]
This make sense. Requirement for merge is that MPT are running fine. Waiting for confirmation then I can merge.

**Comment by kwin** [comment]
> Can you run this change against all Maven Plugin Tools ITs?

You mean https://github.com/apache/maven-plugin-tools being build with `Prun-its` after referencing this PR?

**Comment by michael-o** [comment]
> > Can you run this change against all Maven Plugin Tools ITs?
> 
> You mean https://github.com/apache/maven-plugin-tools being build with `Prun-its` after referencing this PR?

Correct, this code must be in use for these ITs.

**Comment by kwin** [comment]
@michael-o Actually this was thought as an alternative to #213 (as this includes blank values), but we can also obviously apply it on top.

**Comment by kwin** [comment]
Build is successful with `Prun-its`of  https://github.com/apache/maven-plugin-tools after upgrading to this version of plexus-utils.
TBH I don't think there is an IT for this config merging behaviour in MPT.

**Pull request merged**
