### PR TITLE
Using Java 7 instead of Java 1 and custom code

### PR DESCRIPTION
**Pull request by mkarg**
Slightly improving performance and reducing code size by replacement of custom code and Java 1 by Java 7.

### CODE REVIEW

**Comment by michael-o** [comment]
Plexus Utils still requires Java 6. Parts of this PR aren't possible.

**Comment by mkarg** [comment]
@michael-o Is there a branch for future release where I can add it instead of "master", or could we start one?

**Comment by mkarg** [comment]
@michael-o It might be a good idea if Travis could check wheter JRE 7+ code used, to prevent people like me sending such PRs. :-)

**Comment by michael-o** [comment]
We have an enforcer rule for that. In fact, it does use Java 7 code but only if Java 7 is used at runtime.

**Comment by mkarg** [comment]
Right, I memember. Silly me. I will rewrite those Java 7 parts to only be used in case of JRE 7 detected.

**Comment by mkarg** [comment]
I divided my commits into two separate PRs, one for Java 6 and one for Java 7.

Please see https://github.com/codehaus-plexus/plexus-utils/pull/31 for the changes which work on Java 6.

I'd like to propose to open a branch for future Java 7 changes.

**Comment by michael-o** [comment]
As soon as we start using Java 7 these methods get obsolete, I'd deprecate them.

**Pull request closed without merging**
